begin;
select plan(55);
select has_table('public','options_capability_checks','capability audit exists');
select has_table('public','option_contract_observations','contract observations exist');
select has_table('public','option_candidate_evaluations','candidate evaluations exist');
select has_table('public','option_positions','option positions exist');
select has_table('public','collateral_reservations','collateral reservations exist');
select has_table('public','option_lifecycle_events','option lifecycle audit exists');
select has_table('public','option_settlement_events','settlement events exist');
select has_column('public','global_cycles','mode','cycle mode exists');
select has_column('public','global_cycles','selected_asset_class','selected asset class exists');
select has_column('public','global_orders','position_intent','position intent exists');
select has_column('public','option_candidate_evaluations','sanitized_evaluation','evaluation evidence exists');
select ok((select relrowsecurity from pg_class where oid='public.options_capability_checks'::regclass),'capability RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.option_contract_observations'::regclass),'observations RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.option_candidate_evaluations'::regclass),'evaluations RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.option_positions'::regclass),'positions RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.collateral_reservations'::regclass),'collateral RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.option_lifecycle_events'::regclass),'lifecycle RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.option_settlement_events'::regclass),'settlement RLS enabled');
select ok(not has_table_privilege('anon','public.option_positions','SELECT'),'anon cannot read option positions');
select ok(not has_table_privilege('authenticated','public.option_positions','SELECT'),'authenticated cannot read option positions');
select ok(not has_table_privilege('anon','public.option_positions','INSERT'),'anon cannot write option positions');
select ok(not has_table_privilege('authenticated','public.option_positions','UPDATE'),'authenticated cannot update option positions');
select ok(has_table_privilege('service_role','public.option_positions','SELECT'),'backend can observe positions');
select ok(has_table_privilege('service_role','public.option_positions','INSERT'),'backend can create reconciled positions');
select ok(not has_table_privilege('service_role','public.option_lifecycle_events','UPDATE'),'lifecycle audit is append-only');
select ok(not has_table_privilege('service_role','public.option_settlement_events','DELETE'),'settlement audit is append-only');
select has_function('public','activate_global_cycle_mode',array['text','text','timestamp with time zone','text','jsonb'],'mode activation is atomic');
select has_function('public','reserve_option_entry',array['uuid','uuid','text','text','text','text','text','date','numeric','numeric','numeric','numeric','numeric','numeric','numeric','integer','jsonb','timestamp with time zone'],'entry reservation is atomic');
select has_function('public','reserve_option_close',array['uuid','uuid','text','text','text','timestamp with time zone'],'close reservation is atomic');
select has_function('public','record_option_settlement',array['text','uuid','uuid','text','text','text','integer','numeric','timestamp with time zone'],'settlement reconciliation is atomic');
select has_function('public','release_option_collateral',array['text','timestamp with time zone'],'collateral release is atomic');
select ok((select 'security_invoker=true'=any(coalesce(reloptions,'{}')) from pg_class where oid='public.public_option_cycle_envelopes'::regclass),'public option view uses security invoker');
select has_trigger('public','option_contract_observations','option_contract_observations_immutable','observations immutable');
select has_trigger('public','option_candidate_evaluations','option_candidate_evaluations_immutable','evaluations immutable');
select has_trigger('public','option_lifecycle_events','option_lifecycle_events_immutable','lifecycle events immutable');
select has_trigger('public','option_settlement_events','option_settlement_events_immutable','settlements immutable');
select col_is_unique('public','global_orders','client_order_id','client order id remains unique');
select ok((select count(*) = 1 from pg_indexes where schemaname='public' and indexname='global_orders_one_active_option_close_idx'),'one active close index exists');
select ok((select count(*) = 1 from pg_indexes where schemaname='public' and indexname='global_orders_one_entry_per_cycle_idx'),'one entry per cycle index exists');
select has_table('public','option_settlement_materializations','economic settlement ledger exists');
select has_column('public','global_positions','sector','assigned stock retains durable sector');
select has_column('public','collateral_reservations','underlying_symbol','collateral tracks underlying');
select has_column('public','collateral_reservations','sector','collateral tracks sector');
select has_column('public','option_settlement_events','economic_event_key','technical events link economic identity');
select ok((select relrowsecurity from pg_class where oid='public.option_settlement_materializations'::regclass),'economic settlement ledger RLS enabled');
select ok(not has_table_privilege('service_role','public.option_settlement_materializations','DELETE'),'economic settlement ledger is append-only');
select col_is_pk('public','option_settlement_events',array['activity_id','activity_type'],'activity id and type form technical identity');
select ok((select 'security_invoker=true'=any(coalesce(reloptions,'{}')) from pg_class where oid='public.internal_option_cycle_envelopes'::regclass),'internal option view uses security invoker');
select ok(has_table_privilege('service_role','public.internal_option_cycle_envelopes','SELECT'),'backend can read internal option view');
select ok(pg_get_viewdef('public.public_option_cycle_envelopes'::regclass) !~ 'intent_key|client_order_id|broker_order_id','public option view omits broker identifiers');
select has_trigger('public','option_positions','option_positions_consume_collateral','filled position consumes reservation atomically');
select has_trigger('public','option_settlement_materializations','option_settlement_materializations_immutable','economic settlement ledger immutable');
select ok((select prosrc like '%public.global_positions%' from pg_proc where oid='public.reserve_option_entry(uuid,uuid,text,text,text,text,text,date,numeric,numeric,numeric,numeric,numeric,numeric,numeric,integer,jsonb,timestamp with time zone)'::regprocedure),'reservation includes stock risk');
select ok((select prosrc like '%public.option_positions%' from pg_proc where oid='public.reserve_option_entry(uuid,uuid,text,text,text,text,text,date,numeric,numeric,numeric,numeric,numeric,numeric,numeric,integer,jsonb,timestamp with time zone)'::regprocedure),'reservation includes option position risk');
select ok((select prosrc like '%status in (''reserved'', ''consumed'')%' from pg_proc where oid='public.reserve_option_entry(uuid,uuid,text,text,text,text,text,date,numeric,numeric,numeric,numeric,numeric,numeric,numeric,integer,jsonb,timestamp with time zone)'::regprocedure),'reservation includes active durable collateral');

select * from finish();
rollback;