begin;
select plan(35);
select has_table('public','global_cycles','global cycles exist');
select has_table('public','global_cycle_events','cycle events exist');
select has_table('public','global_provider_budgets','global budgets exist');
select has_table('public','global_positions','global positions exist');
select has_table('public','global_orders','global orders exist');
select has_table('public','global_order_events','global order events exist');
select has_table('public','global_approval_requests','global approvals exist');
select has_table('public','global_audit_events','global audit events exist');
select has_sequence('public','global_cycle_events_id_seq','cycle event identity sequence exists');
select ok(has_sequence_privilege('service_role','public.global_cycle_events_id_seq','USAGE'),'backend can allocate cycle event ids');
select has_function('public','activate_global_cycle',array['text','timestamp with time zone'],'atomic activation exists');
select has_function('public','reserve_global_provider_budget',array['text','date','integer'],'atomic provider reservation exists');
select has_function('public','reserve_global_order',array['uuid','uuid','uuid','text','text','text','text','text','text','numeric','numeric','numeric','timestamp with time zone'],'atomic order reservation exists');
select ok((select relrowsecurity from pg_class where oid='public.global_cycles'::regclass),'cycle RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.global_cycle_events'::regclass),'cycle event RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.global_provider_budgets'::regclass),'budget RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.global_positions'::regclass),'position RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.global_orders'::regclass),'order RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.global_order_events'::regclass),'order event RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.global_approval_requests'::regclass),'approval RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.global_audit_events'::regclass),'audit RLS enabled');
select ok(not has_table_privilege('anon','public.global_cycles','SELECT'),'anon cannot query cycles');
select ok(not has_table_privilege('authenticated','public.global_cycles','SELECT'),'authenticated cannot query cycles');
select ok(not has_table_privilege('anon','public.global_orders','SELECT'),'anon cannot query orders');
select ok(not has_table_privilege('authenticated','public.global_orders','SELECT'),'authenticated cannot query orders');
select ok(has_table_privilege('service_role','public.global_cycles','INSERT'),'backend can create cycles');
select ok(has_table_privilege('service_role','public.global_orders','INSERT'),'backend can reserve orders');
select ok(has_table_privilege('service_role','public.global_orders','UPDATE'),'backend can reconcile orders');
select ok(has_table_privilege('service_role','public.global_audit_events','SELECT'),'backend can observe audit');
select col_is_unique('public','global_cycles','cycle_key','cycle key is unique');
select col_is_unique('public','global_orders','intent_key','order intent is unique');
select col_is_unique('public','global_orders','client_order_id','broker client id is unique');
select has_trigger('public','global_orders','capture_global_order_event_trigger','order history trigger exists');
select has_trigger('public','global_order_events','global_order_events_immutable','order events are immutable');
select has_trigger('public','global_audit_events','global_audit_events_immutable','audit events are immutable');
select * from finish();
rollback;